# Generated by Django 4.2.11 on 2026-04-11 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_userprofile_admin_allowed_access_trial_subscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemstatistics',
            options={},
        ),
        migrations.CreateModel(
            name='MFASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_method', models.CharField(choices=[('totp', 'TOTP'), ('sms', 'SMS')], default='totp', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('backup_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('failed_login', 'Failed Login Attempt'), ('password_change', 'Password Change'), ('mfa_setup', 'MFA Setup'), ('mfa_verify', 'MFA Verification'), ('admin_action', 'Admin Action'), ('data_export', 'Data Export'), ('data_delete', 'Data Deletion'), ('profile_update', 'Profile Update'), ('detection_create', 'Detection Created'), ('detection_delete', 'Detection Deleted')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Statistics',
            },
        ),
    ]
