# Generated by Django 4.2.11 on 2026-04-11 12:10

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_permission_role_alter_userprofile_user_type_userrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfasettings',
            name='phone_number',
            field=api.fields.EncryptedCharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mobile_number',
            field=api.fields.EncryptedCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=api.fields.EncryptedCharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='mobile_number',
            field=api.fields.EncryptedCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=api.fields.EncryptedCharField(blank=True, max_length=50),
        ),
    ]
